app:
  name: "backtesting-service"

logging:
  level: "INFO"
  format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

messaging:
  backend: "kafka"
  kafka:
    bootstrap_servers: "redpanda:9092"
    topic: "backtesting-events"
    group_id: "backtesting-group"
    security_protocol: "PLAINTEXT"
